Add month dividers
CSLD/csld-react pull request #3
Opened 2021-04-18 18:40 UTC by mhavelka

## Screenshot
![image](https://user-images.githubusercontent.com/4849644/115156781-41818080-a086-11eb-92b0-6e7aa3e3c9b1.png)

2021-04-18 19:39 UTC, lemmingucwcz requested changes
Zpětnou vazbu ke kódu jsem dal k jednotlivým kusům. Nicméně celé se to dá napsat mnohem jednodušeji a bez toho problému s událostmi v různých letech:

```
let currentMonth = '';

return  (<FinalForm ...
  ...
  {{events.map(event => {
    const lastMonth = currentMonth;
    currentMonth = event.from.toLocaleString('default', { month: 'long', year: 'numeric' });
    return (
      <>
        {currentMonth !== lastMonth && <MonthSeparator>{currentMonth}</MonthSeparator>}
        <CalendarEventPanel key={event.id} event={event} />
      </>
     )
   )}
   ...
```

A zapsat month separator jako:

```
const MonthSeparator: React.FC = ({children}) => {
    const classes = useStyles()
    const { t } = useTranslation('common')
    return <div className={classes.separator}>{children}</div>
}
```

2021-04-18 19:39 UTC, lemmingucwcz commented on src/components/EventCalendar/EventsInMonth.tsx
> +import { CalendarEventDataFragment } from '../../graphql/__generated__/typescript-operations'
Tady by u importu bylo lehce lepší používat absolutní cestu (předpokládám, že to takhle dalo IDE)

2021-04-18 19:39 UTC, lemmingucwcz commented on src/components/EventCalendar/EventCalendarListPanel.tsx
> +    const transformEventsByMonth = (events: Array<CalendarEventDataFragment>): EventsByMonth => {
Tahle funkce se dá vyhodit mimo tělo (funkci) komponenty. Obecně chceme render funkci komponenty udržet co nejkratší a nejpřehlednější.

2021-04-18 19:39 UTC, lemmingucwcz commented on src/components/EventCalendar/EventCalendarListPanel.tsx
> +type EventsByMonth = Array<Array<CalendarEventDataFragment>>
Tenhle typ není potřeba vůbec definovat, Typescript si ho odvodí.

2021-04-18 19:39 UTC, lemmingucwcz commented on src/components/EventCalendar/CalendarEventPanel.tsx
> -
Tyhle prázdné řádky prosím nemaž, jsou tam pro přehlednost.

2021-04-18 19:39 UTC, lemmingucwcz commented on src/components/EventCalendar/EventCalendarListPanel.tsx
> +            const monthOfEvent = parseDateTime(event.from).getMonth()
Celé tohle má jednu zásadní chybu a to že se do sebe budou (mohouú motat události ve stejném měsíci z různých let.

2021-04-18 19:40 UTC, lemmingucwcz commented on src/components/EventCalendar/EventsInMonth.tsx
> +const MonthSeparator = ({ monthNumber }: LineWithMonthProps) => {
`LineWithMonthProps` by se měly jmenovat `MonthSeparatorProps`

2021-04-19 13:49 UTC, closed without merging

2021-04-19 13:49 UTC, mhavelka commented
Addressed in different PR.